In [16]:
%load_ext autoreload
%autoreload 2

import numpy as np
import ipyvolume as ipv
import cv2
import matplotlib.pyplot as plt

from slib.lie_algebra import random_rot3, random_trans3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Draw a single plane
Parts taken from [Multi view notebooks](https://github.com/maxcrous/multiview_notebooks)

In [14]:
nx, ny = (2,2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
X, Y = np.meshgrid(x, y)
# for i in range(nx):
#     for j in range(ny):
#         print(X[j,i], Y[j,i])

Z = 0.5*X + 0.5
ipv.figure()
ipv.plot_surface(X, Z, Y, color="orange")

# fig = ipv.pylab.figure(figsize=(15, 15), width=800)
ipv.xlim(-2.0, 2.0)
ipv.ylim(-2.0, 2.0)
ipv.zlim(-2.0, 2.0)
ipv.pylab.view(azimuth=40, elevation=-150)

ipv.show()

In [47]:
fx = 600
fy = 600
cx = 1280 /2
cy = 720 /2
K = np.array(
    [
        [fx, 0.0, cx],
        [0.0, fy, cy],
        [0.0,0.0,1.0]
    ]
)
print(K)
R = random_rot3()
t = random_trans3()
print(t.shape)
extrinsic = np.vstack((R, t.T))
print(extrinsic.shape)
n = np.array([[0,0,1]])
print(n.shape)
extrinsic = np.c_[ extrinsic, np.eye(3) ] 
print('ee ',extrinsic.shape)

e = np.concatenate([R, t], axis=1)
e = np.vstack([e, [[0,0,0,1]]]) 
print(e.shape)
print(np.linalg.norm(e-extrinsic))

camera_center = -R.T @ t

print(R)
print(t)
print(camera_center)

[[600.   0. 640.]
 [  0. 600. 360.]
 [  0.   0.   1.]]
(3, 1)
(4, 3)
(1, 3)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [ ]:
def init_3d_plot(box_3d, plane_3d):
    """ Initializes a ipyvolume 3d plot and centers the 
        world view around the center of the plane.
        
    Returns: 
        fig (ipyvolume.pylab.figure): A 3D plot. 
    """
    plane_3d_x_center = plane_3d.x
    plane_3d_y_center = plane_3d.y

    fig = ipv.pylab.figure(figsize=(15, 15), width=800)
    ipv.xlim(box_3d.xmin, bx_3d.xmax)
    ipv.ylim(box_3d.ymin, box3d.ymax)
    ipv.zlim(box_3d.zmin, box3d.zmax)
    ipv.pylab.view(azimuth=40, elevation=-150)
    return fig